export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const SEARCH_BY_TITLE = 'SEARCH_BY_TITLE';
export const GETMOVIES_ALL = 'GETMOVIES_ALL';
export const GETMOVIES_SUCCESS = 'GETMOVIES_SUCCESS';

export const GETMOVIES_ACTION = 'GETMOVIES_ACTION';
export const GETMOVIES_ADVENTURES = 'GETMOVIES_ADVENTURES';

export const GET_MOVIE_DETAIL = "GET_MOVIE_DETAIL"
